# Generated by Django 4.0 on 2021-12-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
